### ISSUE TITLE
I tried it... (axmol latest)  and got this errors

### ISSUE THREAD

**Issue by aismann** [DelinWorks/DarkDimensions#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\WelcomeScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C2248	'ax::PhysicsShape::_cpShapes': cannot access protected member declared in class 'ax::PhysicsShape'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp	56	
Error	C2248	'ax::PhysicsShape::_cpShapes': cannot access protected member declared in class 'ax::PhysicsShape'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Wall.cpp	28	
Error	C2660	'ax::PhysicsWorld::rayCast': function does not take 5 arguments	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp	266	
Error	C2248	'ax::PhysicsWorld::_cpSpace': cannot access protected member declared in class 'ax::PhysicsWorld'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	51	
Error	C2248	'ax::PhysicsWorld::_cpSpace': cannot access protected member declared in class 'ax::PhysicsWorld'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	52	
Error	C2248	'ax::ui::TextField::_textFieldRenderer': cannot access protected member declared in class 'ax::ui::TextField'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\custom_nodes\ui\uiTextField.cpp	60	
Error	C2248	'ax::ui::TextField::_textFieldRenderer': cannot access protected member declared in class 'ax::ui::TextField'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\custom_nodes\ui\uiTextField.cpp	61	
Error	C2248	'ax::ui::TextField::_textFieldRenderer': cannot access protected member declared in class 'ax::ui::TextField'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\custom_nodes\ui\uiTextField.cpp	134	
Error	C2248	'ax::ui::TextField::_textFieldRenderer': cannot access protected member declared in class 'ax::ui::TextField'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\custom_nodes\ui\uiTextField.cpp	136	
Error	C2039	'deltaTime': is not a member of 'ax::PhysicsWorld'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp	258	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\AppDelegate.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\AppDelegate.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\AppDelegate.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\EmptyScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\EmptyScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\EmptyScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\CatPlayer.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Player.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Player.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Player.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Wall.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Wall.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\Entities\Wall.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\fmod\FMODAudioEngine.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\fmod\FMODAudioEngine.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\fmod\FMODAudioEngine.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameSingleton.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameSingleton.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameSingleton.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\WelcomeScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\WelcomeScene.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\proj.win32\main.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	178	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\proj.win32\main.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	681	
Error	C3861	'glfwGetWin32Window': identifier not found (compiling source file D:\______\aismann\__bugs_axmol\DarkDimensions\proj.win32\main.cpp)	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\shared_scenes\GameUtils.h	698	
Error	C3861	'isAwake': identifier not found	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	206	
Error	C2039	'isAwake': is not a member of 'ax::Node'	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	206	
Error (active)	E0135	class "ax::Node" has no member "isAwake"	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	206	
Error (active)	E0265	member "ax::PhysicsWorld::_cpSpace" (declared at line 409 of "D:\______\aismann\axmol\core\physics\CCPhysicsWorld.h") is inaccessible	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	51	
Error (active)	E0265	member "ax::PhysicsWorld::_cpSpace" (declared at line 409 of "D:\______\aismann\axmol\core\physics\CCPhysicsWorld.h") is inaccessible	DarkDimensions	D:\______\aismann\__bugs_axmol\DarkDimensions\Classes\GameplayScene.cpp	52

**Comment by DelinWorks** [comment]
I don't use latest axmol commit, I use `https://github.com/DelinWorks/axmol/tree/dev-2` which has modifications that makes the game project compile.

**Comment by aismann** [comment]
Thanks. works now.
I use this : [e2aa5e8](https://github.com/DelinWorks/DarkDimensions/commit/e2aa5e8e756bc52a2da02da20d710f4f63a03ab5)

No `useColliderBatching `found.

And it looks good for me ...no speed issue here

**Comment by DelinWorks** [comment]
edit map with tiled and add more tiled

**Comment by aismann** [comment]
I got this one now (sorry)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3536	'w1': cannot be used before it is initialized	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	202	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	112	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	112	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	113	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	113	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	168	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	168	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	170	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	170	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	172	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	172	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	173	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	173	
Error	C2065	'ONE_WAY_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	181	
Error	C2065	'OPPOSITE_WAY_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	184	
Error	C2065	'RIGHT_ONLY_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	187	
Error	C2065	'LEFT_ONLY_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	190	
Error	C2065	'DISABLE_JUMP_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	193	
Error	C2065	'WALL_JUMP_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	196	
Error	C2065	'DISABLE_TURN_COLLISION_INDEX': undeclared identifier	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	199	
Error	C2660	'Wall::createEntity': function does not take 3 arguments	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	201	
Error	C2665	'ax::Node::addChild': no overloaded function could convert all the argument types	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	202	
Error	C2039	'playerDirection': is not a member of 'CatPlayer'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	213	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	221	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	221	
Error	C2039	'map': is not a member of 'Math'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	222	
Error	C3861	'map': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	222	
Error	C2039	'hex2argb': is not a member of 'ColorConversion'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	236	
Error	C3861	'hex2argb': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	236	
Error	C2039	'hex2argb': is not a member of 'ColorConversion'	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	245	
Error	C3861	'hex2argb': identifier not found	DarkDimensions	C:\d\__DelinWorks\axmol\DarkDimensions\Classes\Nodes\TiledMap.cpp	245	

```

**Comment by DelinWorks** [comment]
do you have rhe helper folder in the project?

**Comment by aismann** [comment]
![image](https://user-images.githubusercontent.com/8652787/223324613-cc43bbfa-6fcb-411e-b6f5-f7b80f021c64.png)

**Comment by aismann** [comment]
I think I have a mix of different version.

**Comment by aismann** [comment]
Ok. Its run.
But I getting an exeption with 
![image](https://user-images.githubusercontent.com/8652787/223334630-4e16c58c-f93c-490b-a5ba-82475ea6bf2e.png)

Which is correct:
![image](https://user-images.githubusercontent.com/8652787/223334559-a468e66a-04cf-48d6-ba69-d98cdffe42f7.png)

**Comment by DelinWorks** [comment]
make sure the layer "solid" is active and there in the tiled editor

**Comment by aismann** [comment]
Ok  (seems 'csv' encoding is needed) => : done. works now

**Comment by aismann** [comment]
Igetting this:
![image](https://user-images.githubusercontent.com/8652787/223638327-dbcc5a2b-836b-4c13-a882-b4af7d4bf08b.png)

**Comment by DelinWorks** [comment]
This example doesn't work anymore because its outdated, I've made a better example more suitable for this bug: 
[ColliderPerformanceTest.zip](https://github.com/DelinWorks/DarkDimensions/files/10921288/ColliderPerformanceTest.zip)
it uses axmol latest

**Comment by aismann** [comment]
Ok is this ok:
![image](https://user-images.githubusercontent.com/8652787/223742976-04439145-092a-4da8-ad8d-31061641263e.png)

**Comment by DelinWorks** [comment]
yes

**Comment by DelinWorks** [comment]
I think maybe creating too many shapes is wrong, you'd need some kind of batching system which I created, something like a grid-based algorithm or a marching squares or Moore neighborhood algorithms; I've only implemented grid-based batching which works great for my use-case: 

![image](https://user-images.githubusercontent.com/45469625/223755878-6ff54fc3-a6ef-40c9-bf40-3767b0d9506a.png)

**Comment by aismann** [comment]
> I think maybe creating too many shapes is wrong

Thats correct !

**Comment by DelinWorks** [comment]
I think a collision system something like a `TMXTiledMapCollision` needs to be implemented where it uses a batching algorithm like the ones i mentioned so that ppl don't have to go through the trouble @aismann

**Comment by aismann** [comment]
which line on wall.cpp?
```
wall_body->getFirstShape()->_cpShapes[0]->filter = cpShapeFilterNew(1, 1, 1);
cpBodySetType(wall_body->getCPBody(), CP_BODY_TYPE_STATIC);
```

**Comment by aismann** [comment]
> I think a collision system something like a `TMXTiledMapCollision` needs to be implemented 
Thats is no physics then. Right?

**Comment by DelinWorks** [comment]
> which line on wall.cpp?

Both

> Thats is no physics then. Right?

What do you mean I don't understand what you're trying to say

**Comment by DelinWorks** [comment]
line 29 on this repo its just I dont have time to edit the axmol latest engine code so that these 2 lines work

**Comment by aismann** [comment]
i can test it now
