### ISSUE TITLE
Works on my phone.

### ISSUE THREAD

**Issue by aismann** [DelinWorks/DarkDimensions#4]
...but there is no goal at the moment right?

**Comment by DelinWorks** [comment]
Thanks! yeah there is no goal at the moment. It needs to be implemented, I'm just working on integrating tiled editor with this game so that making maps can be much easier, also still working on refining parallax and particle systems, also physics system is a mess so yeah 😅 of course the goal is to go through the other end of the level (the opening colored in green) 
If you touch that hitbox it will load the next level!

![image](https://user-images.githubusercontent.com/45469625/224855476-8980be33-0378-4b65-8d77-6813a2b1e99a.png)

**Comment by aismann** [comment]
A good idea is to generate "levels" via programming.

**Comment by DelinWorks** [comment]
woah that feels extremely hard 😅 I'll see what i can do, thanks!

**Comment by aismann** [comment]
> woah that feels extremely hard 😅 I'll see what i can do, thanks!
You can "optimise/fix it on tiled" and learning whats was wrong and fix it on your "room generater sources"

**Comment by johnspeny** [comment]
> A good idea is to generate "levels" via programming.

Do you mean something like using pelin noise generator algorithm?. Thats the only one i can think of.

**Comment by aismann** [comment]
> > A good idea is to generate "levels" via programming.
> 
> Do you mean something like using pelin noise generator algorithm?. Thats the only one i can think of.

Yes and after pelin noise generation you can go over the result and check some rule with your room generator: 
- startpoint
- goul reachable
- remove unreach places or make it reachable

**Comment by johnspeny** [comment]
@aismann Last I checked, you had implemented or forked a game pad controller. Could you add it here aswell. Platformer games like these really need it. I haven't personally run this project, but I will get time and do run it.

**Comment by DelinWorks** [comment]
A cool interaction would be walls that have certain color and these walls will block you from moving through if you have a different color from these walls and you can press a button to switch your color to pass through these walls, just a cool distraction that makes the game a bit of a challenge!

**Comment by aismann** [comment]
Keys, Buttons, etc and corresponding doors/walls, etc

**Comment by johnspeny** [comment]
Is that where DD is heading?, a reference of an already existing game or mechanic is appreciated. I am lost what DD is supposed to be or have.

**Comment by DelinWorks** [comment]
Don't worry everything will be clear when the first playable build is released!

**Comment by johnspeny** [comment]
Meanwhile I think i was seeing rocket science in the appDelegate.cpp, it has so many questionable parts that i have never seen in a normal appDelegate.

**Comment by DelinWorks** [comment]
@aismann A good idea is to generate "levels" via programming.

when you think about it you'll notice that it's nearly impossible to tell a piece of semi-conductors to generate something playable, and that playable thing can contain walls that you can't jump on, obstacles, walls that you can jump on, one way platforms, other way platforms, left or right only walls, walls that need to be color matched so you can pass through, triggers that unlock a path, keys that have gradual progress of events to winning, secret coins that need a path to be provided to get them, so yeah I think letting players create their own levels is way more convenient, then again I might be wrong and it might actually be easy 🤔 sorry for deleted comment though by mistake, thought it was mine 😅

**Comment by aismann** [comment]
Its like a maze generater. not more

**Comment by aismann** [comment]
Close IT
